String.toLocaleString({
	"en": {
		"title": "Report: Japan Earthquake Fundraising Project through purchasing iDaily Pro",
		"page_intro": "<p>An 8.9-magnitude earthquake hit off the east coast of Japan on Friday 11 March 2011. The quake triggered a 23-foot tsunami that battered Japan's coast, killing thousands and causing massive destruction to northeastern Japan. To raise funds for the victims of the disaster, all the proceeds　(JPY 1,145,511 <sup>*1</sup>) from <a href='http://itunes.apple.com/en/app/idaily-pro/id390691023?mt=8' class='high'>iDaily&nbsp;Pro</a> <strong>from 3.11 through 3.31</strong> have been donated to <a href='http://www.jrc.or.jp/contribute/help/l4/Vcms4_00002074.html'>Japanese Red Cross Society</a>.</p><p>Thank you all for your help!</p>",
		"page_sup": "<li>*1 This is the amount after Apple's 30% cut from the sales.</li>",
		"target_amount": "Fundraising Goal: ¥1,000,000",
		"amount": "1,145,511<span>JPY</span>",
		"desc": "Total amount till 3.31",
		"support": "<p>Support us or you also need iDaily Pro,<br/>click the button below</p><a class='button' href='itms://itunes.apple.com/en/app/idaily-pro/id390691023?mt=8#' onclick='this.blur();'><span>Support</span></a>",
		"title_report": "Current <span>Progress</span>",
		"title_user_voice": "<span>Voices</span> of Users #idaily",
		"title_made_possible": "What Made This <span>Possible</span>",
		"title_comments": "Your <span>Comments</span>",
	},
	"ja": {
		"title": "iDaily Proの東北関東大震災の募金プロジェクトの終了報告",
		"page_intro": "<p>3月11日 午後2時46分頃、三陸沖を震源とする非常に強い地震が発生し、これにより東北地方を中心として広い範囲で大きな被害が生じております。</p><p>被災された方々を支援する為、弊社のiPhoneアプリ <a href='http://itunes.apple.com/jp/app/idaily-pro/id390691023?mt=8' class='high'>iDaily&nbsp;Pro</a> の<strong>3月11日〜3月31日の売り上げ全額の1,145,511円 <sup>*1</sup>を<a href='http://www.jrc.or.jp/contribute/help/l4/Vcms4_00002074.html'>日本赤十字社</a>に寄付しました。</strong>みなさまのご支援を心から感謝しております。</p><p>被災し亡くなられた全ての方々の冥福と生きておられる方々の幸運をお祈りいたします。</p>",
		"page_sup": "<li>*1 Apple社により30%手数料相当額を控除された後の金額となります。</li>",
		"target_amount": "目標金額：1,000,000円",
		"amount": "1,145,511<span>円</span>",
		"desc": "3月31日まで",
		"support": "<p>iDaily ProをApp Storeにてご購入頂くことで</p><a class='button' href='itms://itunes.apple.com/ja/app/idaily-pro/id390691023?mt=8#' onclick='this.blur();'><span>応援する</span></a>",
		"title_report": "<span>進捗</span>のご報告",
		"title_user_voice": "<span>利用者</span>の声 #idaily",
		"title_made_possible": "このページを<span>可能に</span>したのは",
		"title_comments": "<span>コメント</span>を投稿",
	},
	"zh_CN": {
		"title": "iDaily Pro - 日本东北大地震募捐统计报告",
		"page_intro": "<p>2011年3月11日14时46分发生的日本东北地方太平洋近海地震及其引发的海啸已造成东北部沿岸大范围的破坏和伤亡。</p><p>为了支援受灾地区，我们已将3月11日开始到3月底的 <a href='http://itunes.apple.com/cn/app/idaily-pro/id390691023?mt=8' class='high'>iDaily&nbsp;Pro</a> 的收入1,145,511日元<sup>*1</sup>全额捐给<a href='http://www.jrc.or.jp/contribute/help/l4/Vcms4_00002074.html'>日本红十字会</a>，虽然相比地震对人们造成的巨大的财产和心灵上的打击，我们的捐款微不足道，但希望灾区的人们能感受到我们的心意。</p><p>让我们为地震中遇难的人们祈祷，为幸存的人们祝福！",
		"page_sup": "<li>*1 扣除AppStore的30%手续费以后的金额。</li>",
		"target_amount": "目标募捐金额：1,000,000日元",
		"amount": "1,145,511<span>日元</span>",
		"desc": "3月31日截止",
		"support": "<p>如果您赞同我们的行为并需要iDaily Pro，<br/>请点击下面的按钮</p><a class='button' href='itms://itunes.apple.com/ja/app/idaily-pro/id390691023?mt=8#' onclick='this.blur();'><span>支 持</span></a>",
		"title_report": "<span>进度</span>汇报",
		"title_user_voice": "<span>用户</span>反馈 #idaily",
		"title_made_possible": "感谢以下的这些<span>分享</span>",
		"title_comments": "给我们<span>留言</span>",
	},
	"kr": {
		"title": "iDaily Pro - 일본 동북대지진 피해자 돕기 기부금 레포트",
		"page_intro": "<p>3월 11일 14시 46분 경 미야기 현 센다이 동쪽의 산리쿠오키(三陸沖) 해역에서 모멘트 규모 9.0의 강한 지진이 일어났습니다. 아울러, 태평양 연안 지역은 추가로 지진 해일이 강타하여 더욱 큰 피해를 입었습니다. </p><p>일본 지진 피해 주민들을 돕기 위해  본사는 3월 11일부터 3월말까지의 <a href='http://itunes.apple.com/kr/app/idaily-pro/id390691023?mt=8' class='high'>iDaily&nbsp;Pro</a> 의 수입<sup>*1</sup>을 전부 기부할것 입니다. 여러분들의 도움과 지원으로 힘이 되여 주셨으면 합니다. </p><p>이번 대지진에 이은 쓰나미로 희생된 일본인들의 명복을 빌며 하루빨리 슬픔과 재난을 극복하길 진심으로 기원합니다.</p>",
		"page_sup": "<li>*1 애플사로부터 30% 수수료를 덜어낸후의 금액입니다.</li>",
		"target_amount": "목표기부금：1,000,000엔",
		"amount": "1,145,511<span>엔</span>",
		"desc": "3월31일부터",
		"support": "<p>iDaily Pro를 구입하시려면 아래버튼을 클릭하십시오.</p><a class='button' href='itms://itunes.apple.com/ja/app/idaily-pro/id390691023?mt=8#' onclick='this.blur();'><span>구입하기</span></a>",
		"title_report": "현재 <span>통계수치</span>",
		"title_user_voice": "애용자들의 <span>목소리</span> #idaily",
		"title_made_possible": "<span>이 웹사이트는 이렇게 만들어 졌습니다</span>",
		"title_comments": "<span>코멘트</span> 달기",
	}
});
